apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delivery
resources:
  - namespace.yaml
  - domain-services.yaml
  - services.yaml
  - kafka.yaml
  - kafka-topic-job.yaml
patches:
  - path: patches/service-probes.yaml
