CREATE TABLE product_skus (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, product_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(100) NOT NULL, price DECIMAL(10,2) NOT NULL, stock INT UNSIGNED NOT NULL DEFAULT 0,
 status VARCHAR(20) NOT NULL DEFAULT 'OFF_SALE', version BIGINT UNSIGNED NOT NULL DEFAULT 1,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 PRIMARY KEY(id), UNIQUE KEY uk_product_skus_name(product_id,name), INDEX idx_product_skus_product(product_id),
 CONSTRAINT fk_product_skus_product FOREIGN KEY(product_id) REFERENCES products(id), CHECK(price>0), CHECK(stock>=0), CHECK(status IN ('ON_SALE','OFF_SALE'))
);
ALTER TABLE products ADD COLUMN image_id BIGINT UNSIGNED NULL;
ALTER TABLE cart_items ADD COLUMN sku_id BIGINT UNSIGNED NULL, ADD COLUMN sku_version BIGINT UNSIGNED NULL, ADD INDEX idx_cart_sku(user_id,sku_id);
ALTER TABLE shops ADD COLUMN address_region VARCHAR(100) NULL, ADD COLUMN address_detail VARCHAR(200) NULL, ADD COLUMN address_phone VARCHAR(20) NULL;
ALTER TABLE orders ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID', ADD COLUMN refund_status VARCHAR(20) NOT NULL DEFAULT 'NOT_REFUNDED', ADD COLUMN remark VARCHAR(500) NULL, ADD COLUMN cancel_reason VARCHAR(200) NULL, ADD COLUMN completed_at DATETIME(3) NULL, ADD COLUMN user_address_snapshot JSON NULL, ADD COLUMN shop_address_snapshot JSON NULL;
ALTER TABLE order_items ADD COLUMN sku_id BIGINT UNSIGNED NULL, ADD COLUMN sku_name VARCHAR(100) NULL, ADD COLUMN image_url VARCHAR(500) NULL;
CREATE TABLE user_addresses (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id BIGINT UNSIGNED NOT NULL,recipient VARCHAR(50) NOT NULL,phone VARCHAR(20) NOT NULL,region VARCHAR(100) NOT NULL,detail VARCHAR(200) NOT NULL,is_default BOOLEAN NOT NULL DEFAULT FALSE,deleted_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(id),INDEX idx_addresses_user(user_id,deleted_at),CONSTRAINT fk_addresses_user FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE images (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,url VARCHAR(500) NOT NULL,content_type VARCHAR(100) NOT NULL,size BIGINT UNSIGNED NOT NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id)
);
CREATE TABLE payments (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,order_id BIGINT UNSIGNED NOT NULL,payment_number VARCHAR(64) NOT NULL,amount DECIMAL(10,2) NOT NULL,status VARCHAR(20) NOT NULL,idempotency_key VARCHAR(100) NOT NULL,paid_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_payments_order(order_id),UNIQUE KEY uk_payments_key(idempotency_key),CONSTRAINT fk_payments_order FOREIGN KEY(order_id) REFERENCES orders(id)
);
CREATE TABLE refunds (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,order_id BIGINT UNSIGNED NOT NULL,refund_number VARCHAR(64) NOT NULL,amount DECIMAL(10,2) NOT NULL,status VARCHAR(20) NOT NULL,completed_at DATETIME(3) NULL,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),PRIMARY KEY(id),UNIQUE KEY uk_refunds_order(order_id),CONSTRAINT fk_refunds_order FOREIGN KEY(order_id) REFERENCES orders(id)
);
