apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../
  - external-config.yaml
patches:
  - path: replicas.yaml
  - path: external-config-patch.yaml
  - path: remove-local-kafka.yaml
  - path: topic-job-patch.yaml
